### ISSUE TITLE
Specification for sendTransaction RPC

### ISSUE THREAD

**Issue by edjroz** [andrewnguyen22/interview-test#3]
Procedure should be able to send a transaction.

mock Failure Response
```
{
    "error": {
        "code": <HTTP_ERROR_CODE>,
        "title": <string>
    }
}
```

further discussion should be made to:
- Clarify response object
- What type of payload should be sent to process the transaction, we currently have a newTransaction function that creates a transaction, but will this RPC receive also addresses ?

@andrewnguyen22

**Comment by andrewnguyen22** [comment]
Payload: `none`

The task is to use the rawTx func to send an autogenerated transaction. 
So, if I hit the endpoint, I want it to send that transaction.

Response: `transaction hash` and/or `error`
